### ISSUE TITLE
Comprehensive tests for continuous integration

### ISSUE THREAD

**Issue by daegontaven** [daegontaven/AlphaHooks#13]
## Problem
Currently the CI tests do not test across multiple platforms for compatibly issue.

## Tasks
The tests should include:
- [ ] UI tests using [pytest-qt](https://github.com/pytest-dev/pytest-qt) or `QTest`
- [ ] Core tests to ensure components are stable
- [ ] Library tests
- [ ] Support for Windows on [Appveyor](https://ci.appveyor.com/project/daegontaven/alphahooks)
- [ ] Support Mac OSX
- [ ] Support most distros of linux
